# Generated by Django 5.2.7 on 2025-11-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('monitor', 'Monitor'), ('socio', 'Socio')], default='socio', max_length=10),
        ),
    ]
