# Generated by Django 5.2.7 on 2025-12-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasio', '0002_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='biografia',
        ),
    ]
